# Generated by Django 6.1.1 on 2026-09-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
